### ISSUE TITLE
Codeblock line-numbers

### ISSUE THREAD

**Issue by kennetpostigo** [kennetpostigo/rdn#3]
For some reason the first codeblock on any page will not show the line numbers for each line of code. However all subsequent codeblocks on the same page will have the line-numbers. It's an odd but and I opened an issue [here](https://github.com/PrismJS/prism/issues/1111). Although I'm not entirely sure about this being a bug in the highlighter component code or prismjs code. Rather I think it may have to do with css being overwritten. Main reason I believe that is that the highlighting used to work well and correctly and only just now did I see this problem. Heres a [tweet](https://twitter.com/kennetpostigo/status/840757506716622848) to prove it.

**Comment by anmonteiro** [comment]
Started looking at this one, looks like Prism hooks are a global thing, and when you set them up the first time (in `CodeBlock`'s render function), the `complete` hook has already been fired.

My intuition tells me we should just set up the line numbering hook on Prism itself at the top-level, but the `CodeHighlighter` component still needs a `func` the way it is set up currently (even just an empty thing works).

I'm happy to put a PR together, let me know how you wanna proceed.

**Comment by kennetpostigo** [comment]
Please do @anmonteiro . The codehighlighter repo is private let me make it public then I'll send you a link.

**Comment by kennetpostigo** [comment]
Heres the repo: https://github.com/hyperfuse/rad-components the highlighter module is in the packages folder

**Comment by kennetpostigo** [comment]
@anmonteiro sorry for the delay a little behind on work. Will review and create release for highlight component and merge PR as soon as I can.
